PropertyAgency.Application/Areas/Admin/Controllers/EmployeeController.cs
namespace PropertyAgency.Application.Areas.Admin.Controllers
{
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using PropertyAgency.Data;
    using PropertyAgency.Models.EntityModels;


    /// <summary>
    /// Controller with Basic CRUD operations.
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class EmployeeController : Controller
    {
        private PropertyAgencyContext db = new PropertyAgencyContext();

        // GET: Admin/Employee
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Admin/Employee/Details/5
        public ActionResult Details(string id)
        {
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Admin/Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Employee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumberConfirmed,LockoutEndDateUtc,AccessFailedCount")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Admin/Employee/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Employee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Exclude = "EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumberConfirmed,LockoutEndDateUtc,AccessFailedCount")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Admin/Employee/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Employee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PropertyAgency.Application/Areas/Admin/Controllers/LandlordController.cs
namespace PropertyAgency.Application.Areas.Admin.Controllers
{
    using System.Web.Mvc;
    using PropertyAgency.Models.BindingModels;
    using PropertyAgency.Services;

    [Authorize(Roles = "Admin, Moderator")]
    public class LandlordController : Controller
    {
        private LandlordService landlordService;

        public LandlordController()
        {
            this.landlordService = new LandlordService();
        }
        // GET: Admin/Admin
        public ActionResult Index()
        {
            return View("");
        }
        [HttpGet]
        public ActionResult Add()
        {
            return this.View();
        }

        /// <summary>
        /// Adding new Landlord to our Database by given BindingModel which come from our Form.
        /// </summary>
        /// <param name="landlordsBindingModel"></param>
        /// <returns>ActionResult(New Landlord)</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Add([Bind(Include = "FullName, PhoneNumber, IsAcceptingAnimals")] LandlordsBindingModel landlordsBindingModel)
        {
            if (ModelState.IsValid)
            {
                this.landlordService.AddLandlord(landlordsBindingModel);
                return this.RedirectToAction("Index", "ControlPanel");
            }
            return this.View(landlordsBindingModel);
        }
    

        /// <summary>
        /// Delete Landlord by Given Id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("DeleteLandlord/{id:regex([0-9]+)}")]
        public ActionResult DeleteLandlord(int? id)
        {
            this.landlordService.Delete(id);
            
            return RedirectToAction($"Show/Landlords", "Properties", new { area = "" });
        }
    }
}

PropertyAgency.Application/Areas/Admin/Controllers/PropertyController.cs
namespace PropertyAgency.Application.Areas.Admin.Controllers
{
    using System.Web.Mvc;
    using PropertyAgency.Models.ViewModels.Property;
    using PropertyAgency.Services;
    using System.Web;
    using PropertyAgency.Models.EntityModels;

    [Authorize(Roles = "Admin, Moderator")]
    public class PropertyController : Controller
    {
        private PropertyService propertyService;

        public PropertyController()
        {
            this.propertyService = new PropertyService();
        }
        // GET: Admin/Property
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Add()
        {
            PropertyFormViewModel model = this.propertyService.GeneratePropertyViewModel();
            return this.View(model);
        }

        /// <summary>
        /// Adding new Property to our Database by given ViewModel which come from our Form.
        /// </summary>
        /// <returns>ActionResult(New Property)</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Add([Bind(Include = "FullAddress, ApartmentSize, NumberOfRooms, IsActive, Type, UrlPicture, Price, LandlordId")] PropertyFormViewModel propertyFormViewModelgModel, HttpPostedFileBase upload)
        {

            if (ModelState.IsValid)
            {
                
                this.propertyService.AddProperty(propertyFormViewModelgModel);

                return this.RedirectToAction("Index", "ControlPanel");
            }
            PropertyFormViewModel model = this.propertyService.GeneratePropertyViewModel();
            return this.View(model);
        }

        /// <summary>
        /// Delete single Property by clicking on Delete button which sends Id to our Action.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("DeleteProperty/{id:regex([0-9]+)}")]
        public ActionResult DeleteProperty(int? id)
        {
            this.propertyService.Delete(id);
            return this.RedirectToAction($"ShowAll", "Properties", new { area = "" });
        }
    }
}

PropertyAgency.Application/Areas/Admin/Controllers/TenantController.cs
namespace PropertyAgency.Application.Areas.Admin.Controllers
{
    using System.Web.Mvc;
    using PropertyAgency.Models.BindingModels;
    using PropertyAgency.Services;

    [Authorize(Roles = "Admin, Moderator")]
    public class TenantController : Controller
    {
        /// <summary>
        /// Tenants Services is the logic behind the Controller
        /// </summary>
        private TenantService tenantService;
      
        public TenantController()
        {
            this.tenantService = new TenantService();
        }
        [HttpGet]
        public ActionResult Add()
        {
            return this.View();
        }
        /// <summary>
        /// Add new Tenant from Control Panel which takes BindingModel
        /// </summary>
        /// <param name="tenantsBindingModel"></param>
        /// <returns>ActionResult or a New Tenant</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Add([Bind(Include = "FullName, PhoneNumber, Description")] TenantsBindingModel tenantsBindingModel)
        {
            if (ModelState.IsValid)
            {
                this.tenantService.AddTenant(tenantsBindingModel);
                return this.RedirectToAction("Index", "ControlPanel");
            }
            // If Faild return to Form
            return this.View(tenantsBindingModel);
        }

        /// <summary>
        /// Delete Landlord by Given Id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("DeleteTenant/{id:regex([0-9]+)}")]
        public ActionResult DeleteTenant(int? id)
        {
            this.tenantService.Delete(id);

            return RedirectToAction($"Show/Tenants", "Properties", new { area = "" });
        }
    }
}

PropertyAgency.Application/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")*@
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/adminPanel.css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    
</head>
<body>

    <div class="nav-side-menu">
        <div class="brand">Admin Panel</div>
      
        <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

        <div class="menu-list">

            <ul id="menu-content" class="menu-content collapse out">
               
               
                    <li data-toggle="collapse" data-target="#products" class="collapsed active">
                        <a href="#"><i class="fa fa-users fa-lg"></i> New Clients <span class="arrow"></span></a>
                    </li>
                    <ul class="sub-menu collapse" id="products">
                        <li>@Html.ActionLink("Add Landlord", "Add", "Landlord")</li>
                        <li>@Html.ActionLink("Add Tenant", "Add", "Tenant")</li>
                    </ul>

                    <li data-toggle="collapse" data-target="#service" class="collapsed">
                        <a href="#"><i class="fa fa-home fa-lg"></i> New Property <span class="arrow"></span></a>
                    </li>
                    <ul class="sub-menu collapse" id="service">
                        <li>@Html.ActionLink("Add Property", "Add", "Property")</li>
                    </ul>

                   
                    @if (User.IsInRole("Admin"))
                    {
                        <li data-toggle="collapse" data-target="#employees" class="collapsed">
                            <a href="#"><i class="fa fa-users fa-lg"></i> Employees <span class="arrow"></span></a>
                        </li>
                    <ul class="sub-menu collapse" id="employees">
                        <li>@Html.ActionLink("New Employee", "Register", "Account", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Show Employees", "Index", "Employee", new { area = "Admin" }, null)</li>
                    </ul>
                    }
                    <li class="back"><i class="glyphicon glyphicon-arrow-left"></i>  @Html.ActionLink("Back", "Index", "Home", new { area = "" }, null)</li>
       
            </ul>
        </div>
    </div>

    <div id="footer" class="container body-content">
        @RenderBody()

        <footer>
            <p>&copy; @DateTime.Now.Year - All Rights Reserved</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>