PropertyAgency.Application/Areas/Admin/Controllers/ControlPanelController.cs
namespace PropertyAgency.Application.Areas.Admin.Controllers
{
    using System.Web.Mvc;

    [Authorize(Roles = "Admin")]
    public class ControlPanelController : Controller
    {
        // GET: Admin/ControlPanel
        public ActionResult Index()
        {
            return View("");
        }
    }
}

PropertyAgency.Application/Controllers/PropertyInfoController.cs
namespace PropertyAgency.Application.Controllers
{
    using System.Web.Mvc;
    using PropertyAgency.Models.ViewModels.Landlord;
    using PropertyAgency.Models.ViewModels.Property;
    using PropertyAgency.Models.ViewModels.Tenant;
    using PropertyAgency.Services;

    /// <summary>
    /// This Controller is used to Show our information about Properties and Clients
    /// </summary>
    [Authorize]
    [RoutePrefix("Properties")]
    public class PropertyInfoController : Controller
    {
        private readonly PropertyService propertyService;
        private readonly LandlordService landlordService;
        private readonly TenantService tenantService;

        public PropertyInfoController()
        {
            this.propertyService = new PropertyService();
            this.landlordService = new LandlordService();
            this.tenantService = new TenantService();
        }

        /// <summary>
        /// Here we Show All our Properties no matter what type are they (Sale or Rent)
        /// </summary>
        /// <param name="page">This param is send to our Pager or Pagination which will separate our data in pages with size of 10 or 20 items</param>
        /// <returns></returns>
        [HttpGet]
        [Route("ShowAll")]
        public ActionResult ShowAll(int? page)
        {
            ShowPropertiesViewModel model = this.propertyService.GetProperies(page);
            return this.View(model);
        }

        /// <summary>
        /// Here we Show only the properties that are under a Rent.
        /// </summary>
        /// <param name="page">The same as the Previous Action</param>
        /// <returns></returns>
        [HttpGet]
        [Route("Show/Rent/")]
        public ActionResult Rent(int? page)
        {
            ShowPropertiesViewModel model = this.propertyService.GetProperiesForRent(page);
            return this.View(model);
        }

        /// <summary>
        /// Here we Show only the properties that are for Sale.
        /// </summary>
        /// <param name="page">The same as the Previous Action</param>
        /// <returns></returns>
        [HttpGet]
        [Route("Show/Sale/")]
        public ActionResult Sale(int? page)
        {
            ShowPropertiesViewModel model = this.propertyService.GetProperiesForSale(page);
            return this.View(model);
        }
        /// <summary>
        /// Here we Show our Landlords.
        /// </summary>
        /// <param name="page">The same as the Previous Action</param>
        /// <returns></returns>
        [HttpGet]
        [Route("Show/Landlords")]
        public ActionResult Landlords(int? page)
        {
            LandlordsViewModel model = this.landlordService.GetAllLandlords(page);
            return this.View(model);
        }
        /// <summary>
        /// Here we Show our Tenants.
        /// </summary>
        /// <param name="page">The same as the Previous Action</param>
        /// <returns></returns>
        [HttpGet]
        [Route("Show/Tenants")]
        public ActionResult Tenants(int? page)
        {
            TenantsViewModel model = this.tenantService.GetAllTenants(page);
            return this.View(model);
        }
    }
}

PropertyAgency.Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Real Estate Agency - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <div class="nav-side-menu">
        <div class="brand">GuTie Managment</div>
        <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

        <div class="menu-list">

            <ul id="menu-content" class="menu-content collapse out">
                <li>

                    <i class="fa fa-home fa-lg"></i>
                    @Html.ActionLink("Home", "Index", "Home")

                </li>
                @if (User.IsInRole("Moderator") || User.IsInRole("Broker") || User.IsInRole("Admin"))
                {
                    <li data-toggle="collapse" data-target="#products" class="collapsed active">
                        <a href="#"><i class="fa fa-users fa-lg"></i> Clients <span class="arrow"></span></a>
                    </li>



                    <ul class="sub-menu collapse" id="products">
                        <li>@Html.ActionLink("Landlords", "Landlords", "PropertyInfo")</li>
                        <li>@Html.ActionLink("Tenants", "Tenants", "PropertyInfo")</li>

                    </ul>

                    <li data-toggle="collapse" data-target="#service" class="collapsed">
                        <a href="#"><i class="fa fa-home fa-lg"></i> Properties <span class="arrow"></span></a>
                    </li>
                    <ul class="sub-menu collapse" id="service">
                        <li>@Html.ActionLink("All", "ShowAll", "PropertyInfo")</li>
                        <li>@Html.ActionLink("Rent", "Rent", "PropertyInfo")</li>
                        <li>@Html.ActionLink("Sale", "Sale", "PropertyInfo")</li>


                    </ul>

                    if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                    {
                        <li>
                            <i class="glyphicon glyphicon-wrench"></i>
                            @Html.ActionLink("Control Panel", "Index", "ControlPanel", new { area = "Admin" }, null)

                        </li>
                    }
                }
                <li data-toggle="collapse" data-target="#new" class="collapsed">
                    <a href="#">
                        <i class="fa fa-globe fa-lg"></i> About
                        <span class="arrow"></span>
                    </a>
                </li>
                <ul class="sub-menu collapse" id="new">
                    <li>@Html.ActionLink("Our Company", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>

                <li>
                    @Html.Partial("_LoginPartial")
                </li>
            </ul>



        </div>
    </div>

    <div id="footer" class="container body-content">
        @RenderBody()

        <footer>
            <p>&copy; @DateTime.Now.Year - All Rights Reserved</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PropertyAgency.Application/Views/Shared/_ShowPropertiesPartial.cshtml
@model PropertyAgency.Models.ViewModels.Property.ShowPropertiesViewModel

@{
    ViewBag.Title = "_ShowPropertiesPartial";
}


<div class="table table-bordered">
    <table class="table table-responsive">
        <thead>
        <tr>
            <th>Снимки</th>
            <th class="full-address">Full Address</th>
            <th class="apartment-size">Apartment Size</th>
            <th class="number-of-rooms">Number of rooms</th>
            <th class="property-isActive">Is Available?</th>
            <th class="price">Price</th>
            <th class="landlord-name">Landlord</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var property in Model.PropertyInfoViewModels)
        {
            if (property.IsActive)
            {
            <tr style="background: #38c938;">
                <td><img class="img-rounded" src="@property.UrlPicture" width="150" height="150"/></td>
                <td class="full-address">&nbsp;@property.FullAddress</td>
                <td class="apartment-size">&nbsp;@property.ApartmentSize кв.м</td>
                <td class="number-of-rooms">&nbsp;@property.NumberOfRooms</td>
                <td class="property-isActive">&nbsp;@property.IsActive</td>
                <td class="price">&nbsp;@property.Price лв.</td>
                <td class="landlord-name">&nbsp;@property.LandlordName</td>
                <td>
                    <a href="../../EditProperty/@property.Id">Edit</a> |
                    <a href="../../DeleteProperty/@property.Id">Delete</a>
                </td>
            </tr>
            }
            else
            {
                <tr style="background: red;">
                    <td><img class="img-rounded" src="@property.UrlPicture" width="150" height="150" /></td>
                    <td class="full-address">&nbsp;@property.FullAddress</td>
                    <td class="apartment-size">&nbsp;@property.ApartmentSize кв.м</td>
                    <td class="number-of-rooms">&nbsp;@property.NumberOfRooms</td>
                    <td class="property-isActive">&nbsp;@property.IsActive</td>
                    <td class="price">&nbsp;@property.Price лв.</td>
                    <td class="landlord-name">&nbsp;@property.LandlordName</td>
                    <td>
                        <a href="../../EditProperty/@property.Id">Edit</a> |
                        <a href="../../DeleteProperty/@property.Id">Delete</a>
                    </td>
                </tr>
            }
        }

        </tbody>
    </table>
</div>